### ISSUE TITLE
[20000 BLU] Crash Problem

### ISSUE THREAD

**Issue by bluehackmaster** [the-blu/blu-browser-android#14]
Version : 0.0.15-17

Package : net.bluehack.blu
FilePath : /data/user/0/net.bluehack.blu/files
Phone ModelSM-G935K
Android Version : 7.0
Brand : samsung
Device : hero2ltektt
Display : NRD90M.G935KKKU1DQL1
Finger Print : samsung/hero2ltektt/hero2ltektt:7.0/NRD90M/G935KKKU1DQL1:user/release-keys
Model : SM-G935K
Product : hero2ltektt
Tags : release-keys
Time : 1512037372000
Total Internal memory : 26800832512
Available Internal memory : 11429761024

Stack : 
======= 
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.mozilla.focus.widget.DockLayout.setSites(java.util.List)' on a null object reference
 at org.mozilla.focus.fragment.UrlInputFragment$onViewCreated$5.onChanged(UrlInputFragment.kt:230)
 at org.mozilla.focus.dock.DockManager$4$1.run(DockManager.java:243)
 at android.os.Handler.handleCallback(Handler.java:751)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6646)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

Cause : 
======= 
****  End of current Report ***

**Comment by bluehackmaster** [comment]
commit : b8748bf9fecf17fe3960f0cfd84b3cd06a330707

done.
